update

diff --git a/lxc/lxc-create-container b/lxc/lxc-create-container
--- a/lxc/lxc-create-container
+++ b/lxc/lxc-create-container
@@ -38,7 +38,7 @@ idmap_next_available_id()
 
 print_help()
 {
-    echo "Usage: $0 container-name distribution [release] [-- lxc-options...]" >&2
+    echo "Usage: $0 container-name distribution release [config-file] [-- lxc-options...]" >&2
 }
 
 argn=0
@@ -56,6 +56,7 @@ while true; do
     0) name="$1" ;;
     1) dist="$1" ;;
     2) release="$1" ;;
+    3) config_file="$1" ;;
     *) print_help; exit 1
     esac
 
@@ -65,6 +66,11 @@ done
 
 if [[ -z "$dist" || -z "$release" ]]; then
     print_help
+    exit 1
+fi
+
+if [[ -n "$config_file"  && ! -f "$config_file" ]]; then
+    echo "Error: config file doesn't exist" >&2
     exit 1
 fi
 
@@ -113,26 +119,36 @@ printable_params()
     done
 }
 
-cat > "$cfg_path" <<EOF
-# LXC configuration for ${name} - created by lxc-create-container
-#   name: ${name}
-#   dist: ${lxc_dist}
-#   release: ${lxc_release}
-#   lxc-options: $(printable_params "$@")
-#   date: $(date --iso-8601=seconds)
-
-EOF
-
 default_conf=$(lxc-config lxc.default_config)
 if [[ -f "$default_conf" ]]; then
     cat "$default_conf" >> "$cfg_path"
+else
+    echo -n >> "$cfg_path"
+fi
+
+if [[ -n "$config_file" ]]; then
+    cat "$config_file" >> "$cfg_path"
 fi
 
 uid_start=$(idmap_next_available_id /etc/subuid $IDMAP_CHUNK)
 gid_start=$(idmap_next_available_id /etc/subgid $IDMAP_CHUNK)
 
-echo "root:${uid_start}:${IDMAP_CHUNK}" >> "/etc/subuid"
-echo "root:${gid_start}:${IDMAP_CHUNK}" >> "/etc/subgid"
+uid_line="root:${uid_start}:${IDMAP_CHUNK}"
+gid_line="root:${gid_start}:${IDMAP_CHUNK}"
+
+undo_idmap()
+(
+    grep -v -F -x "$uid_line" /etc/subuid > /etc/subuid.new
+    mv /etc/subuid{.new,}
+
+    grep -v -F -x "$gid_line" /etc/subgid > /etc/subgid.new
+    mv /etc/subgid{.new,}
+)
+
+trap undo_idmap EXIT
+
+echo "$uid_line" >> "/etc/subuid"
+echo "$gid_line" >> "/etc/subgid"
 
 cat >> "$cfg_path" <<EOF
 lxc.id_map = u 0 ${uid_start} 100000
@@ -142,3 +158,5 @@ EOF
 lxc-create -n "${name}" -f "${cfg_path}" -B zfs \
  -o "${cfg_dir}/create.log" -l INFO \
  -t download -- -d "${lxc_dist}" -r "${lxc_release}" -a amd64 "$@"
+
+trap - EXIT
